// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkerTracking.Data;

namespace WorkerTracking.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201123065743_pepe")]
    partial class pepe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkerTracking.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnName("Abbreviation")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 5001,
                            Abbreviation = "PO",
                            Name = "Product Owner"
                        },
                        new
                        {
                            RoleId = 5002,
                            Abbreviation = "PM",
                            Name = "Project Manager"
                        },
                        new
                        {
                            RoleId = 5003,
                            Abbreviation = "TL",
                            Name = "Team Leader"
                        },
                        new
                        {
                            RoleId = 5004,
                            Abbreviation = "FD",
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            RoleId = 5005,
                            Abbreviation = "BD",
                            Name = "Backeck Developer"
                        },
                        new
                        {
                            RoleId = 5006,
                            Abbreviation = "FS",
                            Name = "Fullstack Developer"
                        },
                        new
                        {
                            RoleId = 5007,
                            Abbreviation = "QA",
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            RoleId = 5008,
                            Abbreviation = "UX",
                            Name = "User Experience"
                        },
                        new
                        {
                            RoleId = 5009,
                            Abbreviation = "FA",
                            Name = "Functional Analyst"
                        },
                        new
                        {
                            RoleId = 5010,
                            Abbreviation = "GD",
                            Name = "Graphic Designer"
                        },
                        new
                        {
                            RoleId = 5011,
                            Abbreviation = "HR",
                            Name = "Human Resources"
                        },
                        new
                        {
                            RoleId = 5012,
                            Abbreviation = "TS",
                            Name = "Technical Support"
                        });
                });

            modelBuilder.Entity("WorkerTracking.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StatusId")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.HasKey("StatusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = 101,
                            Name = "Active"
                        },
                        new
                        {
                            StatusId = 102,
                            Name = "Inactive"
                        },
                        new
                        {
                            StatusId = 103,
                            Name = "Pause"
                        },
                        new
                        {
                            StatusId = 104,
                            Name = "Vacations"
                        },
                        new
                        {
                            StatusId = 105,
                            Name = "In a meeting"
                        });
                });

            modelBuilder.Entity("WorkerTracking.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WorkerTracking.Entities.Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WorkerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("character varying(70)")
                        .HasMaxLength(70);

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoUrl")
                        .HasColumnName("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnName("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("WorkerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("WorkerTracking.Entities.WorkersByTeam", b =>
                {
                    b.Property<Guid>("WorkersByTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WorkersByTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkersByTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkersByTeams");
                });

            modelBuilder.Entity("WorkerTracking.Entities.Team", b =>
                {
                    b.HasOne("WorkerTracking.Entities.WorkersByTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkerTracking.Entities.Worker", b =>
                {
                    b.HasOne("WorkerTracking.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkerTracking.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkerTracking.Entities.WorkersByTeam", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkerTracking.Entities.WorkersByTeam", b =>
                {
                    b.HasOne("WorkerTracking.Entities.Team", "Team")
                        .WithMany("WorkersByTeamId")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkerTracking.Entities.Worker", "Worker")
                        .WithMany("WorkersByTeamId")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
